# Generated by Django 6.0.1 on 2026-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_risco', models.IntegerField()),
                ('classificacao', models.CharField(max_length=20)),
                ('erros_coerencia', models.JSONField(default=list)),
                ('riscos_identificados', models.JSONField(default=list)),
                ('problemas_estrutura', models.JSONField(default=list)),
                ('red_flags', models.JSONField(default=list)),
                ('tempo_processamento', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='usuarios.diagrama')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
