# Generated by Django 6.0.1 on 2026-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_analisediagrama_imagem_infografico'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisediagrama',
            name='fontes_rag',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
